# Generated by Django 5.2.7 on 2025-10-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام وبسایت')),
                ('discription', models.TextField(max_length=300, verbose_name='توضیحات')),
                ('category', models.CharField(max_length=20, verbose_name='دسته بندی')),
                ('lable', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='پوستر')),
                ('link', models.CharField(max_length=50, verbose_name='لینک')),
            ],
        ),
    ]
