# Generated by Django 5.2.7 on 2025-10-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_authentication_service_backend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='pagespeed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
