# Generated by Django 5.2.7 on 2025-10-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_service_pagespeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='service',
            name='pagespeed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
