# Generated by Django 5.2.7 on 2025-10-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_image_1_service_image_2_service_image_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='discription',
        ),
        migrations.AddField(
            model_name='service',
            name='long_discription',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name=' توضیحات بلند '),
        ),
        migrations.AddField(
            model_name='service',
            name='short_discription',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name=' توضیحات کوتاه '),
        ),
    ]
