# Generated by Django 5.2.7 on 2025-10-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_service_discription_service_long_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='short_discription',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name=' توضیحات کوتاه '),
        ),
    ]
