# Generated by Django 5.2.7 on 2025-11-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_service_short_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='pages',
            field=models.IntegerField(default='1', max_length=3, verbose_name='تعداد صفحات'),
        ),
        migrations.AlterField(
            model_name='service',
            name='long_discription',
            field=models.TextField(blank=True, null=True, verbose_name=' توضیحات بلند '),
        ),
    ]
