# Generated by Django 5.2.7 on 2025-11-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_service_pages_alter_service_long_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='database',
            field=models.CharField(default='SQLite', verbose_name='پایگاه داده'),
        ),
        migrations.AddField(
            model_name='service',
            name='media_management_system',
            field=models.CharField(blank=True, null=True, verbose_name='سیستم مدیریت محتوا'),
        ),
        migrations.AddField(
            model_name='service',
            name='multi_language_support',
            field=models.CharField(blank=True, null=True, verbose_name='قابلیت چند زبانه بودن'),
        ),
        migrations.AddField(
            model_name='service',
            name='target_devices',
            field=models.CharField(blank=True, null=True, verbose_name='دستگاه های هدف'),
        ),
    ]
