# Generated by Django 5.2.7 on 2025-11-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_service_database_service_media_management_system_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='multi_language_support',
        ),
        migrations.AddField(
            model_name='service',
            name='language',
            field=models.CharField(blank=True, null=True, verbose_name='زبان'),
        ),
    ]
