# Generated by Django 5.2.7 on 2026-04-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام وبسایت')),
                ('short_discription', models.TextField(blank=True, max_length=100, null=True, verbose_name=' توضیحات کوتاه ')),
                ('long_discription', models.TextField(blank=True, null=True, verbose_name=' توضیحات بلند ')),
                ('category', models.CharField(max_length=20, verbose_name='دسته بندی')),
                ('lable', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='پوستر')),
                ('link', models.CharField(max_length=50, verbose_name='لینک')),
                ('frontend', models.CharField(blank=True, max_length=100, null=True)),
                ('backend', models.CharField(blank=True, max_length=100, null=True)),
                ('hosting', models.CharField(blank=True, max_length=100, null=True)),
                ('authentication', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=100, null=True)),
                ('pagespeed', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('pages', models.IntegerField(default='1', max_length=3, verbose_name='تعداد صفحات')),
                ('media_management_system', models.CharField(blank=True, null=True, verbose_name='سیستم مدیریت محتوا')),
                ('database', models.CharField(default='SQLite', verbose_name='پایگاه داده')),
                ('language', models.CharField(blank=True, null=True, verbose_name='زبان')),
                ('target_devices', models.CharField(blank=True, null=True, verbose_name='دستگاه های هدف')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='تصویر')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='تصویر')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='تصویر')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='تصویر')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='تصویر')),
                ('image_6', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='تصویر')),
                ('image_7', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='تصویر')),
                ('image_8', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='تصویر')),
            ],
        ),
    ]
