# Generated by Django 5.2.7 on 2026-06-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(max_length=40, verbose_name='دسته بندی'),
        ),
    ]
