# Generated by Django 5.2.7 on 2026-06-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='site_type',
            field=models.CharField(choices=[('functional', 'کاربردی'), ('ui-ux', 'طرح UI/UX')], default='functional', max_length=20, verbose_name='نوع سایت'),
        ),
    ]
